apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.project }}-{{ .Values.global.environment }}-app-service
  labels:
    {{- include "common.labels" . | indent 4 }}
    app.kubernetes.io/component: app
    deployment: {{ .Values.global.project }}-{{ .Values.global.environment }}-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "deployment.selectorLabels" . | indent 4 }}
