apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.global.project }}-{{ .Values.global.environment }}-cron
  labels:
    {{- include "common.labels" . | indent 4 }}
    app.kubernetes.io/component: app
  {{- if eq (.Values.annotateDeployment | default false) true }}
  annotations:
    timestamp: {{ now | date "2006-01-02_15-04-05" | quote }}
  {{- end }}
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      backoffLimit: 3
      ttlSecondsAfterFinished: 600
      template:
        metadata:
          name: {{ .Values.global.project }}-{{ .Values.global.environment }}-cron
          labels:
            {{- include "common.labels" . | indent 12 }}
            app.kubernetes.io/component: app
        spec:
          securityContext:
            fsGroup: 1000
          imagePullSecrets:
            - name: {{ .Values.imagePullSecret }}
          volumes:
          {{- include "common.volumes" . | indent 10 -}}
          {{- include "drupal.volumes" . | indent 10 -}}
          restartPolicy: Never
          containers:
          {{- include "drupal.cron.containerSpec" (merge (dict "_isJob" true) .) | indent 10 -}}
