kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.global.project }}-{{ .Values.global.environment }}-app-backups-pvc
  labels:
    {{- include "common.labels" . | indent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: {{ .Values.backupStorage.size }}
  storageClassName: {{ .Values.backupStorage.class }}
