apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.project }}-{{ .Values.global.environment }}-app
  labels:
    {{- include "common.labels" . | indent 4 }}
    app.kubernetes.io/component: app
  {{- if eq (.Values.annotateDeployment | default false) true }}
  annotations:
    timestamp: {{ now | date "2006-01-02_15-04-05" | quote }}
  {{- end }}
data:
  database.host: {{ .Values.appDatabaseHost | quote }}
  database.port: "3306"
  drupal-base-uri: {{ .Values.ingress.host }}
  drush-site-uri: {{ include "drupal.appUri" . | quote }}
