kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.global.project }}-{{ .Values.global.environment }}-app-pvc
  labels:
    {{- include "common.labels" . | indent 4 }}
    app.kubernetes.io/component: storage
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: {{ .Values.appStorage.size }}
  storageClassName: {{ .Values.appStorage.class }}
