{{- if eq (.Values.dedicatedFrontend.enable | default false) true }}
{{- if or (not (.Values.dedicatedFrontend.ingress.blockedPaths | empty)) (not (.Values.dedicatedFrontend.ingress.redirectedPaths | empty)) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.project }}-{{ .Values.global.environment }}-frontend-admin-common-config
  labels:
    {{- include "common.labels" . | indent 4 }}
    app.kubernetes.io/component: app
data:
  nginx.conf: |
    daemon                          off;
    worker_processes                auto;
    error_log                       /proc/self/fd/2 debug;

    pid        /tmp/nginx.pid;

    events {
        worker_connections          1024;
        multi_accept                on;
    }

    http {
        include                     /etc/nginx/mime.types;
        default_type                application/octet-stream;

        client_body_temp_path /tmp/client_temp;
        proxy_temp_path       /tmp/proxy_temp_path;
        fastcgi_temp_path     /tmp/fastcgi_temp;
        uwsgi_temp_path       /tmp/uwsgi_temp;
        scgi_temp_path        /tmp/scgi_temp;

        log_format json_combined escape=json
              '{'
                '"time_local":"$time_iso8601",'
                '"client_ip":"$http_x_forwarded_for",'
                '"remote_addr":"$remote_addr",'
                '"remote_user":"$remote_user",'
                '"request":"$request",'
                '"status":"$status",'
                '"body_bytes_sent":"$body_bytes_sent",'
                '"request_time":"$request_time",'
                '"http_referrer":"$http_referer",'
                '"http_user_agent":"$http_user_agent",'
                '"request_id":"$request_id"'
              '}';

        access_log /proc/self/fd/1 json_combined;

        # error_log off; # Maybe needed for disabling php errors.

        send_timeout                60s;
        sendfile                    on;
        client_body_timeout         60s;
        client_header_timeout       60s;
        client_max_body_size        500m;
        client_body_buffer_size     16k;
        client_header_buffer_size   4k;
        large_client_header_buffers 8 16K;
        keepalive_timeout           75s;
        keepalive_requests          100;
        reset_timedout_connection   off;
        tcp_nodelay                 on;
        tcp_nopush                  on;
        server_tokens               off;
        underscores_in_headers      off;

        upload_progress             uploads 1m;

        brotli                      on;
        brotli_static               on;
        brotli_comp_level           1;
        brotli_types                application/atom+xml
                                    application/geo+json
                                    application/javascript
                                    application/json
                                    application/ld+json
                                    application/manifest+json
                                    application/rdf+xml
                                    application/rss+xml
                                    application/vnd.ms-fontobject
                                    application/wasm
                                    application/x-font-opentype
                                    application/x-font-truetype
                                    application/x-font-ttf
                                    font/eot
                                    font/opentype
                                    font/otf
                                    image/bmp
                                    image/svg+xml
                                    image/vnd.microsoft.icon
                                    image/x-icon
                                    image/x-win-bitmap
                                    text/cache-manifest
                                    text/css
                                    text/javascript
                                    text/markdown
                                    text/plain
                                    text/x-component
                                    text/x-cross-domain-policy
                                    text/xml
                                    application/x-javascript
                                    application/x-web-app-manifest+json
                                    application/xhtml+xml
                                    application/xml
                                    application/xml+rss;

        gzip                        on;
        gzip_buffers                16 8k;
        gzip_comp_level             1;
        gzip_http_version           1.1;
        gzip_min_length             20;
        gzip_vary                   on;
        gzip_proxied                any;
        gzip_disable                msie6;
        gzip_types                  application/atom+xml
                                    application/geo+json
                                    application/javascript
                                    application/json
                                    application/ld+json
                                    application/manifest+json
                                    application/rdf+xml
                                    application/rss+xml
                                    application/vnd.ms-fontobject
                                    application/wasm
                                    application/x-web-app-manifest+json
                                    application/xhtml+xml
                                    application/xml
                                    font/otf
                                    image/bmp
                                    image/svg+xml
                                    text/cache-manifest
                                    text/calendar
                                    text/css
                                    text/javascript
                                    text/markdown
                                    text/plain
                                    text/vcard
                                    text/vnd.rim.location.xloc
                                    text/vtt
                                    text/x-component
                                    text/x-cross-domain-policy;





        real_ip_header X-Real-IP;
        real_ip_recursive off;




        add_header                  X-XSS-Protection '1; mode=block';
        add_header                  X-Frame-Options SAMEORIGIN;
        add_header                  X-Content-Type-Options nosniff;


        map $uri $no_slash_uri {
            ~^/(?<no_slash>.*)$ $no_slash;
        }

        include conf.d/*.conf;
    }

{{- end }}
{{- end }}