{{- if eq (.Values.dedicatedFrontend.enable | default false) true }}
{{- if not (.Values.dedicatedFrontend.ingress.redirectedPaths | empty) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.project }}-{{ .Values.global.environment }}-frontend-admin-redirect-config
  labels:
    {{- include "common.labels" . | indent 4 }}
    app.kubernetes.io/component: app
data:
  default.conf: |
    server {
      listen {{ .Values.nginxTargetPort | default 8080 | int }} default_server ipv6only=off;

      server_name _;
      # @todo: don't assume https
      return 301 https://{{ .Values.ingress.host }}$request_uri;
    }

    server {
      listen 127.0.0.1:{{ .Values.nginxHealthPort | default 9002 | int }} default_server;

      server_name internal.health;

      location ~ ^/(status|ping)$ {
        allow 127.0.0.1;
        deny all;

        access_log off;

        return 200 "Ok.";
      }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.project }}-{{ .Values.global.environment }}-frontend-admin-redirect-app-service
  labels:
    {{- include "common.labels" . | indent 4 }}
    app.kubernetes.io/component: app
    deployment: {{ .Values.global.project }}-{{ .Values.global.environment }}-frontend-admin-redirect-app-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.nginxTargetPort | default 8080 }}
      protocol: TCP
      name: http
  selector:
  {{- include "deployment.frontendAdminRedirectSelectors" . | indent 4 }}
---
{{- $redirectorImage := (include "frontend-admin.image-name" (dict "name" .Values.dedicatedFrontend.ingress.redirectorImage "tag" .Values.dedicatedFrontend.ingress.redirectorImageTag) | trim ) -}}
{{- include "frontend-admin.deployment" (merge (dict "_deploymentType" "redirect" "_deploymentSelectorName" "deployment.frontendAdminRedirectSelectors" "_image" $redirectorImage) .) }}
{{- end }}
{{- end }}