apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.global.project }}-{{ .Values.global.environment }}-db-backup-restore
  labels:
    {{- include "common.labels" . | indent 4 }}
    app.kubernetes.io/component: app
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-rollback
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 3
  template:
    metadata:
      name: {{ .Values.global.project }}-{{ .Values.global.environment }}-db-backup-restore
      labels:
        {{- include "common.labels" . | indent 8 }}
        app.kubernetes.io/component: app
    spec:
      securityContext:
        fsGroup: 1000
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      volumes:
      {{- include "common.volumes" . | indent 6 -}}
      {{- include "drupal.volumes" . | indent 6 -}}
      restartPolicy: Never
      containers:
  {{- include "drupal.backupRestoreJob.containerSpec" (merge (dict "_isJob" true) .) | indent 6 -}}
{{/*---*/}}
{{/*# @todo: Add job for rolling back files, too.*/}}