{{- if eq .Values.robotsOverride.enable true }}
{{- if .Values.robotsOverride.existingConfig | empty }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.robotsConfName" . | trim }}
  labels:
    {{- include "common.labels" . | indent 4 }}
    app.kubernetes.io/component: app
  {{- if eq (.Values.annotateDeployment | default false) true }}
  annotations:
    timestamp: {{ now | date "2006-01-02_15-04-05" | quote }}
  {{- end }}
data:
  robots.txt: |
    User-agent: *
    Disallow: /
{{- end -}}
{{- end -}}
