{{- if eq .Values.trustedHosts.enable true }}
{{- if .Values.trustedHosts.existingConfig | empty }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.trustedHostsConfigName" . | trim }}
  labels:
    {{- include "common.labels" . | indent 4 }}
    app.kubernetes.io/component: app
  {{- if eq (.Values.annotateDeployment | default false) true }}
  annotations:
    timestamp: {{ now | date "2006-01-02_15-04-05" | quote }}
  {{- end }}
data:
  settings.trusted-hosts.php: |
    <?php

    /**
    * @file
    * Trusted hosts.
    */

    $settings['trusted_host_patterns'] = [
      '^{{ .Values.ingress.host | trim }}$',
      {{- if not (.Values.ingress.additionalHosts | empty) }}
      {{- range .Values.ingress.additionalHosts }}
      '^{{ . | trim }}$',
      {{- end }}
      {{- end }}
      {{- if not (.Values.trustedHosts.additionalHosts | empty) }}
      {{- range .Values.trustedHosts.additionalHosts }}
      '^{{ . | trim }}$',
      {{- end }}
      {{- end }}
    ];

{{- end -}}
{{- end -}}
