{{- if eq .Values.trustedHosts.enable true }}
{{- if .Values.trustedHosts.existingConfig | empty }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.trustedHostsConfigName" . | trim }}
  labels:
    {{- include "common.labels" . | indent 4 }}
    app.kubernetes.io/component: app
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/resource-policy: keep
    helm.sh/hook-weight: "-1"
  {{- if eq (.Values.annotateDeployment | default false) true }}
    timestamp: {{ now | date "2006-01-02_15-04-05" | quote }}
  {{- end }}
data:
  settings.trusted-hosts.php: |
    <?php

    /**
    * @file
    * Trusted hosts.
    */

    $settings['trusted_host_patterns'] = [
      '^{{ .Values.ingress.host | trim | replace "." "\\." }}$',
      {{- if not (.Values.ingress.additionalHosts | empty) }}
      {{- range $host := .Values.ingress.additionalHosts }}
      '^{{ $host | trim | replace "." "\\." }}$',
      {{- end }}
      {{- end }}
      {{- if eq (.Values.dedicatedFrontend.enable | default false) true }}
      '^{{ .Values.dedicatedFrontend.ingress.host | trim | replace "." "\\." }}$',
      {{- if not (.Values.dedicatedFrontend.ingress.additionalHosts | empty) }}
      {{- range $host := .Values.dedicatedFrontend.ingress.additionalHosts }}
      '^{{ $host | trim | replace "." "\\." }}$',
      {{- end }}
      {{- end }}
      {{- if not (.Values.dedicatedFrontend.ingress.redirectedHosts | empty) }}
      {{- range $host := .Values.dedicatedFrontend.ingress.redirectedHosts }}
      '^{{ $host | trim | replace "." "\\." }}$',
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if not (.Values.trustedHosts.additionalHosts | empty) }}
      {{- range $host := .Values.trustedHosts.additionalHosts }}
      '^{{ $host | trim | replace "." "\\." }}$',
      {{- end }}
      {{- end }}
    ];
{{- end -}}
{{- end -}}
